### ISSUE TITLE
前端

### ISSUE THREAD

**Issue by jackalchenxu** [jackalchenxu/jackalchenxu#13]
- 大前端知识
   - yarn 
- Vue
   - 刚开始学Vue，心智模型上改动最大的应该是要熟悉Web页面元素和Vue数据绑定的方式，不要用老方法去从页面元素的javascript动作去操作数据，而是用页面元素绑定Vue数据，然后Vue数据内互操作的流程去思考

**Comment by jackalchenxu** [comment]
## React Syntax

### setState(updater[, callback])
- updater可以是函数，如：
```
this.setState((state, props) => { 
   return { counter: state.counter + props.step }; 
});
```

- 也可以是对象类型: {key: value}
stateChange()会将传入的对象浅层合并到新的state中，如：
```
this.setState({quantity: 2})
```
- 注意，此时用对象类型时，多个setState()对同一个对象更新，会产生新值覆盖旧值的现象：
```
this.setState({quantity: state.quantity + 1});
this.setState({quantity: state.quantity + 1});
```
结果quantity并不是在原来基础上+2，此时需要换用函数方式:
```
this.setState((state) => { 
   return { quantity: state.quantity + 1};
});
this.setState((state) => { 
   return { quantity: state.quantity + 1};
});
```

**Comment by jackalchenxu** [comment]
## Javascript Syntax:

### Object
使用大括号{} 来建立object，称为object literals
```
var object = {};
var player = {
   name: "OneJar",  progress: 23, sayHi: function() { return "hello" },  language1: "Javascript"
};
player.language2 = "Typescript";
```
name， progress等就是对象player的属性，可以在声明时添加，之后也可以额外添加。

ES5添加的`简化`特性：每次要为对象添加/设置属性时，如果属性值的变量名跟属性名相同时，此时可只写变量名，如下：
```
const name = "OneJar";
const progress = 23;
const sayHi = function() { return "hello" };
const language1 = "Javascript";

const player = {name, progress, sayHi, language1};
```
所以，有时候看到这样的代码，别觉得特别奇怪： 
```
const name = "OneJar";
....
........
const player = {name} ;
```

实际上，ES5，ES6还有其他的一些简化写法的规范，详见：
- https://ithelp.ithome.com.tw/articles/10208316
- https://www.sitepoint.com/es6-enhanced-object-literals/

**Comment by jackalchenxu** [comment]
随着React升级，目前React.js小书中关于Context的部分已经过时/legacy code，现在需换成新版，这里总结一下Context在React中的用法：

1.  一般而言，单独生成context.js，其中包含如下代码：

``` js
import { createContext } from "react";
export default createContext();
```
注意这里createContext()函数在内部创建了一个对象，其属性有Provider, Consumer,...

2. 在context分享瀑布(context信息流就好像瀑布一样，从源头流到下游)的源头，比如index.js:

``` js
import { MyContext} from "./context"
...
class Index extends React.Component {
   render() {
      return (<div><MyContext.Provider value={store}>
                      <Header />
                      <Content />
                   </MyContext.Provider></div>)
   }
}

......
const store = createStore(themeReducer);
......
```
store, themeReducer, 参见React.js小书对应代码

3. 在瀑布沿途，均可以获取context，但需要这样写才行：
``` js
import { MyContext} from "./context.js"
class Header extends React.Component {
   static contextType = MyContext;
   .......
   ............ //需要使用到context的时候，用this.context
}
```
有一点要强调的：
- 在要使用Context的组件上，都要写上 `static contextType = MyContext; ` 或者在组件class的外面写：
``` js
class Header extends React.Component {
   ......
}
Header.contextType = MyContext;
```
contextType实际上是组件的属性，赋值了之后(在这里是MyContext)，当Header组件的包含render()，ComponentDidMount()等方法的代码中，当包含this.context，就会触发React内部代码，去获取瀑布中离自己最近的context的值。

**Comment by jackalchenxu** [comment]
### React+TypeScript Cheatsheets
https://github.com/typescript-cheatsheets/react

**Comment by jackalchenxu** [comment]
### npm or yarn,  and npx
- npm或yarn
都是包管理器，一是负责下载包，比如常见的：
`npm install react`  -- 安装React最新版
至于说到哪里去找包，下载包，这都是npm自己内策略实现(从npmjs);  其他语言如Rust或Golang也类似，Rust默认是从crates.io...
yarn可以理解为npm的改良版，下载速度更快（异步多线程），yarn命令行语法跟npm稍有一些不一样。

- npx
npx中的x是eXecuator，负责`执行`，比如常见的：
`npx create-react-app dapp`
npx会尝试检查是否有create-react-app这个可执行档，如果没有，则去临时下载包，安装；然后再执行之前的命令；执行完后再删除之前的临时下载的包，这样不污染环境。

- npx 产生的原因：
  之前没有npx，换成用npm，我们需要这样做：
  1. `npm install some-package`

  2. `./node_modules/.bin/some-package`  (没有办法，要执行就得这样)
   或者这样： 
  在package.json中添加如下scripts：

    ``` json 
    {
       "name": "whatever",
       "version": "1.0.0",
       "scripts": {
         "some-package": "some-package"
       }
    }
  ```

  然后`npm run some-package`

  这样的操作实在太麻烦了，所以出来了npx，完成1+2，还不产生临时文件

**Comment by jackalchenxu** [comment]
### React小书

- (1-3) 前端要解决的一个基本问题：制作出Web Component
Web Component具有高内聚，低耦合的特点，这样方便共享； 跟HTML，浏览器打交道，就免不了要操作DOM（改动状态，数据刷新等），但制作Web component，就是要**避免直接操作DOM**，应该怎么来做？

- (4)Component类
作为Web Component的父类，具备setState()，_renderDOM()，mount(), constructor()方法
   - setState(newState)
   更新component的状态（会调用_renderDOM())
   - _renderDOM(), mount(component, wrapper)
   操作DOM，完成component在Web页面上的刷新
   - constructor(props)
   组件初始化，获取属性配置

 props是父亲组件给子节点的配置参数; state是子节点自身的内部状态
   

- (5) React.js环境
  - npm create-react-app $project_name
  - .....上面的指令最后如果接上`--template typescript` 会使用ts（默认为js）
  - npm run $target, target可以为start, build等，target都列在项目根目录的package.json   

- (6) JSX
我们将会看到的，在后面和React到处可见的，在return()中的，这种html和js混合在一起的，叫JSX对象
``` React
class MyComponment extends React.Component {
   ...
   render() {
      return (<div><h1><Mybutton />...</div>)
   }
}
```
JSX对象存在于React处理的领域；根据最终输出形式的不同（如手机端，PC端，Native端），React会把它们渲染成不同的输出

- (7) render方法
在render方法中的JSX书写格式上，有一些要注意的，比如：
   - 不能返回多个并列的JSX对象，需要在最外面再用一个<div>包裹一下；或者试试React的<Fragement> - 我感觉React希望我们少写一点html
   - 要用{}包裹js表达式的值 (Vue也是一样)

- (8) 组件tree
![img](http://huzidaha.github.io/static/assets/img/posts/19BBE4E2-A12E-4657-BA6A-61484F67FA60.png)

- (9) 事件监听
``` js
class Title extends Component {
  handleClickOnTitle (word, e) {
    console.log(this, word)
  }

  render () {
    return (
      <h1 onClick={this.handleClickOnTitle.bind(this, 'Hello')}>React 小书</h1>
    )
  }
}
```

注意：约定俗成，事件处理函数名都类似 `handleXxx`

- (10,12) 组件state和setState
组件分为：有状态组件和无状态组件(stateless component)
从程序设计角度讲，无状态组件便于测试，无副作用，React把无状态组件称为`函数式组件`，比如：
``` js
const HelloWorld = (props) => {
  const sayHi = (event) => alert('Hello World')
  return (
    <div onClick={sayHi}>Hello World</div>
  )
}
```
HelloWorld接收配置信息props，返回一个无状态组件，其内部实现不包含this.state

但一个业务系统不可能只包含无状态组件，还是要有一些有状态组件，其内部包含状态变迁，实现用户的复杂业务逻辑，比如：
``` js
class LikeButton extends Component {
  constructor () {
    super()
    this.state = { isLiked: false }
  }

  handleClickOnLikeButton () {
    ......
    this.setState({
      isLiked: !this.state.isLiked
    })
  }

  render () {
    return (
      <button onClick={this.handleClickOnLikeButton.bind(this)}>
        {this.state.isLiked ? '取消' : '点赞'} 👍
      </button>
    )
  }
}
```
套路一般是利用constructor来设置初始化状态；业务函数改变状态，当状态被修改，需要重刷新组件时，调用setState(newState)，(之后把该组件的刷新任务放入React内部队列中)，让React来安排调用组件的render()

PS: 不要写xxx.state = value; 不过你写了无无妨，IDE会提示你换用setState() 

- (11) props
   - 编程套路：父组件利用props传递变化的配置信息给子组件，子组件利用props和state来组织自己的状态变化。
父组件Index传递props给子组件LikeButton：
``` js
class Index extends Component {
  render () {
    return (
      <div>
        <LikeButton likedText='已赞' unlikedText='赞' />
      </div>
    )
  }
}
```

   - 子组件LikeButton使用**this.props**，来获取props
   - 默认props:
``` js
  static defaultProps = {
    likedText: '取消',
    unlikedText: '点赞'
  }
```

  - 别尝试在子组件修改父组件传递下来的props，这没有意义

- (13) 渲染列表
信息放在一个列表中，想要渲染的话，使用javascript的map函数：
array.map((element, index) => { /* … */ }))
``` js
<div>
   {users.map((user) => {
      <User user_info={user} />
   })}
</div>
```
不过上面的例子执行时会报错: ![err_img](http://huzidaha.github.io/static/assets/img/posts/85CA5037-99C1-422C-99A4-AADA978C6801.png)
一般情况下，不使用index参数，但React需要用此信息来帮助渲染(为了内部优化)，所以上面的例子应该要修改为：
``` js
<div>
   {users.map((user, index) => {
      <User user_info={user} key={index}/>
   })}
</div>
```

- (14,15,16) 实际构建一个简单的留言小程序
![img](http://huzidaha.github.io/static/assets/img/posts/6A3B65A1-0CEA-4F98-B2E7-DC1D9B4CED83.png)
  - 合理划分父组件和子组件
  - 父组件把动作委托给子组件调用（动作本身仍在父组件定义）
  - 父组件传递信息给子组件
  - 受控组件 - HTML中的input等有其内部状态，并自行维护（比如用户输入了字串，input组件的value会被自动更新），现在要合并入React中，由其组件的state来控制
  - 语法细节

- (17) props与state，信息分享
  - 共享信息需要在一处保管/维护，需要这些信息的组件，可以利用props来传递信息
  - 在多层组件树形结构的项目中，信息从瀑布顶端传递到最低端，面临传props的繁琐的处理，更好的解决方案是Redux

- (18，19) 组件声明周期(constructor, render, componentXXXMount)
新版本react有修改，建议参见[此图](https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/)，即构建-->渲染-->安装(DidMount)，其他的中间状态已经去掉了。
把组件display设置为none时，会触发WillUnMount

- (20) 不做深入研究
- (21) Ref指向DOM节点, 随时在js中使用，实现精细操作
总有一些操作需要我们在js中手动控制DOM，比如之前的评论程序中，用户输入了信息，点击"发布"，此时我们希望评论发布后，输入焦点回到用户名一栏中。

``` js
class CommitSubmit extends React.Component {
   constructor(props) {
      ...
      this.focusInput = React.createRef();
   }
   ...
   handleSubmit() {
      ....
      this.focusInput.current.focus();
   }
   render() {
      ....
        <span>用户名:<input ref={this.focusInput}...>
      ...
   }
}
```

以上是官方推荐的，比较清晰的代码，`this.focusInput.current`会返回DOM节点引用。
Ref不能被滥用。

- (22) props.children和容器类组件
容器类组件（通常是用来安排其容纳的组件的布局），透过props.children来获取容纳的组件列表

- (23)js控制html和css
dangerouslySetInnerHTML和style - JSX的进阶用法

- (24) props类型验证和PropTypes
React新版已经修改了该部分，目前props类型验证已经外移到'prop-type'包来实现，如下是demo：

``` js
import PropTypes from 'prop-types';

class Greeting extends React.Component {
   render() {
      return (<h1>Hello, {this.props.name}</h1>);
   }
}

Greeting.propTypes = {
   name: PropTypes.string
}
```

PropTypes功能就是对props传递过来的信息做检查：检查是否有传(isRequired)，检查类型是否匹配等

PropTypes类型中的基本类型：string, bool, func, number, object, array, symbol
其他类型：node（复合类型）, element, instanceof, oneOf, oneOfType, arrayof, ...

可以看出，移出了React，第三方库比较方便的扩展类型，提供了更多选择，同时也不用受React规范的限制。

- (25,26,27) 评论程序第二版
  - 页面加载完成自动聚焦到评论输入框。
  - 把用户名持久化，存放到浏览器的 LocalStorage 中。页面加载时会把用户名加载出来显示到输入框，用户就不需要重新输入用户名了。
  - 把已经发布的评论持久化，存放到浏览器的 LocalStorage 中。页面加载时会把已经保存的评论加载出来，显示到页面的评论列表上。
  - 评论显示发布日期，如“1 秒前”，”30 分钟前”，并且会每隔 5 秒更新发布日期。
  - 评论可以被删除。
  - 类似 Markdown 的行内代码块显示功能，用户输入的用 \`\` 包含起来的内容都会被处理成用 ```<code\>``` 元素包含。例如输入 \`console.log\` 就会处理成 ```<code>console.log</code>``` 再显示到页面上。

- (28) high order component高阶组件
就是一个函数，传入参数，返回一个组件；这样的组件，没有内部状态变量，比如：
``` js
const CommitList = (props) => {
   return(<div>
      {props.commentList.map((comment, index) => {
         return <Comment handleCommentDelete={props.handleCommentDelete} 
             comment={comment} key={index} index={index}></Comment>
         }})
      </div>)
};
```
还有一种用法就是创建一个包裹组件，其接收一个组件，并返回包裹后的新组件，差别在于新组件有额外一些功能，就像Python的装饰器，比如创建一个包裹组件WrappedComponent，接收一个组件A和参数name，并提供从localStorage获取name的值，返回组件A，其props的data为name值
``` js
export default (WrappedComponent, name) => {
  class NewComponent extends Component {
    constructor () {
      super()
      this.state = { data: null }
    }

    componentWillMount () {
      let data = localStorage.getItem(name)
      this.setState({ data })
    }

    render () {
      return <WrappedComponent data={this.state.data} />
    }
  }
  return NewComponent
}
```
高阶组件的重大意义就在于组件功能复用：把多个组件的重复的逻辑抽取出来，做成高阶组件，多个组件想具备该功能，只需用该高阶组件来包裹/创建即可。
高阶组件与被包裹组件之间的信息，透过props来传递。


- (29) context，React领域的全局变量，参见[update后的代码](https://github.com/jackalchenxu/jackalchenxu/issues/13#issuecomment-1221538353)
提醒一点，context中的变量值可被"瀑布"沿途的子组件修改，所以应用的时候需要先做好读取和修改的规划。

- (30-35) 真正的解决方案：[Redux](https://redux.js.org/)
前一章节提到了context，不过context只是特殊用法，而真正的解决方案应该是Redux
Redux是一组js库，制订出了一套规范接口来保管/使用state，Redux中的几个概念：
  - reducer() 根据旧状态和修改数据，生成新状态（reducer好处在于会比较新旧状态差别，不会无故刷新不用刷新的组件）
  - dispatch() 显式API，用来作为唯一修改state的入口函数（想要修改state，都得call这个函数）
  - createStore() 初始化store，返回的store对象有三个方法可用：getState(), dispatch(), subscribe()
  - subscribe(listener_func) 
   当state被修改时，透过listener_func()来检测并实现刷新（这里说要检测是因为整体state树的某一个分支有修改，很可能对于其他分支上的组件没有影响，此时需要获取子组件old_state值，和子组件新状态值：store.getState().some.deep.branch.value，然后对比，有差异才调用函数进行子组件的重刷）

 具体API信息参见：https://redux.js.org/api/api-reference
 当然了，React小书的作者也提到了，这样干瘪的概念总结，无法让新人从头了解Redux要解决什么样的问题，从哪里一步一步演变过来的，如果对这些概念不了解，可以参考React小书的30-35

- (36-42) React-redux，redux在React上的应用
这部分已经随着React升级发生了变化，有一些做法比如从context获取store已经不推荐；有一些是React推荐的新做法和新API，比如Provider，useDispatch；在使用新旧代码混合代码，会发生了错误。

- (43)
- (44-46)

**Comment by jackalchenxu** [comment]
### React组件进化的方向是：函数式组件

这意味着React小书中的demo code，在以后会变成legacy code；作为教学讲述原理没有问题，但离实战就差了很远。
为啥React要切换到函数式组件(Functional Component)和Hooks?
网络上很多说法，其中一条是React采用函数式组件，才能更好地支持多线程并发。
有一个[例子](https://overreacted.io/zh-hans/how-are-function-components-different-from-classes/)

我作为一个后端开发者，不用太纠结于谁好谁坏，follow the lead即可。

**Comment by jackalchenxu** [comment]
### Redux
Redux是前端javascript库，面向组件编程，以全新的模式来解决“状态保存”，“状态变更”，“组件刷新”的老问题。-- 抱歉，这是我的口水话
> Redux 是個給 JavaScript 應用程式所使用的可預測 state 容器

看了React小书，然后再看[这个](https://chentsulin.github.io/redux/index.html)，会让你有一种膜拜的感觉（想出这个解决方案的人真不简单）

**Comment by jackalchenxu** [comment]
> 有了React, 我们不再直接与DOM API交互，而是指明想让React构建什么，React收到后会帮我们渲染和协调元素。

这就是声明式编程(风格)，我们所知的函数式编程是其中的一个实现概念。

之前出现过的是`指令式`编程(风格)，它符合直觉，要做什么，透过下发指令实现，带来的问题是，如果其他人(甚至包括作者自己，当过了一段较长时间后)，对该项业务不熟悉，则理解该过程很困难，附加效果是要写很多代码注释。

**Comment by jackalchenxu** [comment]
pitch fall
1.  in "Learning React", chapter 6
``` js
<Star key={i} selected={selectedStars > i} />
```
and 
``` js
const Star = (selected: false) => { return (<FaStar color={selected? "red": "gray"} />); }
```

is there something wrong?
here:  when coding like above,  const Star = (selected: false) => { ... } 
selected is "props", and selected.selectd acutally is boolean value, represent star color... we should change code to:

const Star = **{(selected: false)}** => { return (<FaStar color={selected? "red": "gray"} />); }

to unpack the selected bool value 

2. the same error, if happens in react component definition:
``` js
export default function StarRating(totalStars = 5) {
    const [selectedStars] = useState(3);

    return (<Fragment>
        {createArray(totalStars).map((n, i) => <Star key={i} selected={selectedStars > i}/>)}
        <p>{selectedStars} of {totalStars} stars</p>
    </Fragment>);
};
```

the error message in chrome console is alike:
>react-dom.development.js:14887 Uncaught Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:1)
    at createChild (react-dom.development.js:15139:1)
    at reconcileChildrenArray (react-dom.development.js:15404:1)
    at reconcileChildFibers (react-dom.development.js:15821:1)
    at reconcileChildren (react-dom.development.js:19167:1)
    at updateHostComponent (react-dom.development.js:19924:1)
    at beginWork (react-dom.development.js:21618:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)

it surely leave you clueless, where is the problem? don't worry, let look for any error related with your local file.
>

**Comment by jackalchenxu** [comment]
#### ES6新增的“箭头函数”
来自MDN的介绍：
箭头函数表达式的语法比函数表达式更简洁，并且没有自己的this，arguments，super或new.target。
箭头函数表达式更适用于那些本来需要匿名函数的地方，并且它不能用作构造函数。

有了箭头函数，创建函数就不需要繁琐的function等关键词了（箭头函数的另一个作用我们会在后面提到）
``` javascript
const createCompliment = (name) => `${name} : well done!`

console.log(createCompliment("Molly"));

const createPerson = (firstName, lastName) => ({
      firstName, lastName
});    //外面的括号要加，不然报错： unexpected token :
```

另外，箭头函数区别于普通函数的另一点：
- 箭头函数中的this，绑定的是箭头函数定义时作用域的对象；
- 普通函数中的this，绑定的是普通函数使用时作用域的对象 （只在乎是谁调用了它，跟在哪里进行的函数声明没有关系）

如下是例子：
普通函数
``` javascript
var name = 'window';  // window.name = 'window'

var A = {
   name: 'A',
   sayHello: function(){
      console.log(this.name)
   }
}

A.sayHello();         //输出A

var B = {
  name: 'B'
}

A.sayHello.call(B);  //输出B
```

箭头函数
``` javascript
var name = 'window';  // window.name = 'window'

var A = {
   name: 'A',
   sayHello: () => console.log(this.name);
}

A.sayHello();    //输出window
```
在使用箭头函数的例子中，箭头函数定义时没有被其他函数包裹，此时处于最外层的j作用域，this指向window。
想让箭头函数中的this，绑定对象A的name，需要这样写：
``` javascript
var name = 'window';  // window.name = 'window'

var A = {
   name: 'A',
   sayHello: fucntion() {
      var f = () => console.log(this.name); 
      return f
}

let af = A.sayHello();    
af(); //输出window
```
实际上，熟悉Rust中闭包概念的同学，此时箭头函数就是闭包，this捕获的就是当前函数作用域时环境变量

**Comment by jackalchenxu** [comment]
'https://beta.reactjs.org/' is a informative site of 'design pattern'
